mail_google = 'testcolbot1@gmail.com'
mail_outlook = 'testcolbot1@outlook.com'
mail_exchange = 'testcolbot1@outlook.com'
mail_icloud = 'testcolbot1@gmail.com'

password_google = 'testcolbot1QAZ'
password_outlook = 'colbot1QAZ'
password_exchange = 'colbot1QAZ'
password_icloud = 'qazwsxedcrfvtgby'

authorization_google = '/html/body/app-root/app-system/div/header/div/welcome/div/div/div[1]/div[2]/button[1]'
authorization_microsoft = '/html/body/app-root/app-system/div/header/div/welcome/div/div/div[1]/div[2]/button[2]'
authorization_outlook = '/html/body/modal-container/div/div/div/button[1]'
authorization_exchange = '/html/body/modal-container/div/div/div/button[2]'
authorization_icloud = '/html/body/app-root/app-system/div/header/div/welcome/div/div/div[1]/div[2]/button[3]'

googleMailNext =  'identifierNext'
googleInputMail = 'identifierId'
googlePasswordNext = 'passwordNext'
googleInputPassword = 'password'
googleSubmit = 'submit_approve_access'

outlookInputMail = 'i0116'
outlookMailNext = 'idSIButton9'
outlookInputPassword = 'i0118'
outlookPasswordNext = 'idSIButton9'

exchangeInputMail = 'email'
exchangeInputPassword = 'password'
exchangeMailPasswordNext = '/html/body/modal-container/div/div/div/form/button'

icloudInputMail = 'account_profile_email'
icloudInputPassword = 'account_profile_password'
icloudchecbox = 'account_profile_accept_terms'
icloudMailPasswordNext = '/html/body/div/div/div[3]/form/input[4]'